base_url = "https://blog.cscnk52.me"
default_language = "zh-cn"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false

taxonomies = [{ name = "tags" }, { name = "categories" }]

title = "cscnk52"
description = "the blog of cscnk52"
author = "cscnk52"

generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]

lazy_async_image = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "posts", path = "/posts", is_external = false},
  { name = "tags", path = "/tags", is_external = false },
  { name = "about", path = "/about", is_external = false },
]
blog_section_path = "/posts"

force_theme = false
back_link_text = ""

footer = true
footer_copyright = "© 2025 cscnk52"
footer_credits = false

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false
